# Generated by Django 5.1.2 on 2024-10-16 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="api",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=69, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="api_version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="icenter.api"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="version_detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("init_key", models.CharField(max_length=333)),
                ("map_key", models.CharField(max_length=333)),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("method", "Method"),
                            ("endpoint", "Endpoint"),
                            ("parameter", "Parameter"),
                            ("header", "Header"),
                            ("body", "Body"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "component_data_type",
                    models.CharField(
                        choices=[("string", "String"), ("number", "Number")],
                        max_length=20,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="icenter.api_version",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="api_active_version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="icenter.api"
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="icenter.api_version",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("api", "version"), name="unique_api_version"
                    )
                ],
            },
        ),
    ]
