# Generated by Django 5.1.2 on 2024-10-16 10:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("icenter", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="api_active_version",
            new_name="ApiActiveVersion",
        ),
        migrations.RenameModel(
            old_name="api_version",
            new_name="ApiVersion",
        ),
        migrations.RenameModel(
            old_name="version_detail",
            new_name="VersionDetail",
        ),
    ]
