# Generated by Django 5.1.2 on 2024-10-23 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hire_center", "0002_company_candidate_company"),
        ("icenter", "0002_rename_api_active_version_apiactiveversion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="api",
            name="company",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="hire_center.company",
            ),
            preserve_default=False,
        ),
    ]
