# Generated by Django 5.1.2 on 2024-11-04 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("icenter", "0003_api_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiactiveversion",
            name="api",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="icenter.api"
            ),
        ),
        migrations.AlterField(
            model_name="apiactiveversion",
            name="version",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="icenter.apiversion"
            ),
        ),
    ]
