# Generated by Django 5.1.2 on 2024-11-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("icenter", "0004_alter_apiactiveversion_api_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="apiactiveversion",
            name="unique_api_version",
        ),
        migrations.AlterField(
            model_name="versiondetail",
            name="component_data_type",
            field=models.CharField(
                choices=[
                    ("string", "String"),
                    ("number", "Number"),
                    ("array", "Array"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="apiactiveversion",
            constraint=models.UniqueConstraint(
                fields=("api", "version"), name="unique_api_active_version"
            ),
        ),
    ]
