# Generated by Django 5.1.2 on 2024-11-06 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("icenter", "0008_rename_component_type_versiondetail_component_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiactiveversion",
            name="version",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="active",
                to="icenter.apiversion",
            ),
        ),
    ]
