# Generated by Django 5.1.2 on 2024-10-23 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hire_center", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=88)),
                ("token", models.CharField(max_length=333)),
            ],
        ),
        migrations.AddField(
            model_name="candidate",
            name="company",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="hire_center.company",
            ),
            preserve_default=False,
        ),
    ]
