# Generated by Django 5.1.2 on 2024-10-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hire_center", "0002_company_candidate_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="token",
            field=models.CharField(max_length=333, null=True),
        ),
    ]
