# Generated by Django 5.1.2 on 2024-10-29 04:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hire_center", "0003_alter_company_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="token",
        ),
        migrations.AddField(
            model_name="company",
            name="secret_key",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
